site_name: IO-Tracer
nav:
  - Introduction: index.md
  - Quick Start Windows: startwin.md
  - Quick Start Linux: startlinux.md
  - Prolific Submission: prolificsubmission.md
  - Privacy Protection Measures: privacy.md
  - Fields Collected: fields.md
  - Technical Details Linux: technicalnux.md
  - Technical Details Windows: technicalwin.md
theme: readthedocs
